### ISSUE TITLE
crash-81154a65438ba5aaeca73fd502fa4850fbde60f8.tif triggers some Antiviruses

### ISSUE THREAD

**Issue by HeavyTony2** [conda-forge/pillow-feedstock#113]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:  crash-81154a65438ba5aaeca73fd502fa4850fbde60f8.tif is considered as harfmul by some antivirus. See https://www.virustotal.com/gui/file/13b76234bb194c93a9a94653b4dd850ba5498f66f5f64e48e4109e7120cedc71?nocache=1

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by HeavyTony2** [comment]
Nevermind, I just saw this https://github.com/conda-forge/pillow-feedstock/pull/104#issuecomment-1005245444

**Comment by johnbradley** [comment]
I am seeing this problem when I install the pillow using conda. The the `crash-81154a65438ba5aaeca73fd502fa4850fbde60f8.tif` file was still downloaded and picked up by some antivirus software. For example the bad crash file was downloaded to `~/.conda/pkgs/pillow-9.0.0-py310h2f95282_0/info/recipe/Tests/images/crash-81154a65438ba5aaeca73fd502fa4850fbde60f8.tif`
Would it be possible to exclude this file from the conda package?

**Comment by h-vetinari** [comment]
Can you raise a PR to remove the affected images and skip the respective tests?

**Comment by hugovk** [comment]
@johnbradley Which antivirus software?

The file was already moved out of the main Pillow repo due to an AV false positive: 

* https://github.com/python-pillow/Pillow/pull/5561 -> https://github.com/python-pillow/pillow-depends/pull/39

Feel free to do so here too.

And the test is already skipped in code when the file is not found:

* https://github.com/python-pillow/Pillow/blob/6faebd3ff321e7b2dd780950858301e1b2d76db8/Tests/test_tiff_crashes.py#L37

Please could you also report the file to the AV software as a false positive? That would help others. It's a test file to guard against a decoding regression: https://github.com/python-pillow/Pillow/pull/5372, not a virus file.

Thanks!

**Comment by h-vetinari** [comment]
This image has not been removed by #114.

**Comment by jakirkham** [comment]
Sorry, but clarification is that meant to be has been?

**Comment by h-vetinari** [comment]
> Sorry, but clarification is that meant to be has been?

Yes! No idea why I mistyped this, sorry about the false alarm.

**Comment by jakirkham** [comment]
All good. Thanks for clarifying 🙏
